In [1]:
#numpy is a numerical  library
import numpy as np

In [2]:
#one dimention array
A = np.array([1,2,3])

In [3]:
A

array([1, 2, 3])

In [10]:
#mult-dimention array
B = np.array([[1,3,4],
              [2,4,5], 
              [2,4,5]])

In [9]:
B

array([[1, 3, 4],
       [2, 4, 5],
       [2, 4, 5]])

In [13]:
#we use the shape to create the array
one = np.ones((2,3))

In [12]:
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
#uses the shape,its input parameter is a tuple
Zero = np.zeros((3,2))

In [18]:
Zero

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
#creates a constant and populates the array.its parameter is a shape tuple and the constant number
cons = np.full((3,4),7)

In [20]:
cons

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [21]:
#identity matrix,takes in a scaler
idty = np.eye(3)


In [22]:
idty

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])